// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzFl78FzvFSbElM53alb0uxX4b_k6JE-4',
    appId: '1:579360616764:web:19b817c411943e6b546e39',
    messagingSenderId: '579360616764',
    projectId: 'util-check',
    authDomain: 'util-check.firebaseapp.com',
    storageBucket: 'util-check.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9D6Jp1buWEKWyf6I4zeutaeyjfNGHErE',
    appId: '1:579360616764:android:288ae35c1563338b546e39',
    messagingSenderId: '579360616764',
    projectId: 'util-check',
    storageBucket: 'util-check.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXw2yZldjF4aqzjnDBa26MoDcWzKqFTIg',
    appId: '1:579360616764:ios:15e1e32d92bbe35b546e39',
    messagingSenderId: '579360616764',
    projectId: 'util-check',
    storageBucket: 'util-check.firebasestorage.app',
    iosBundleId: 'com.example.checkutil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXw2yZldjF4aqzjnDBa26MoDcWzKqFTIg',
    appId: '1:579360616764:ios:15e1e32d92bbe35b546e39',
    messagingSenderId: '579360616764',
    projectId: 'util-check',
    storageBucket: 'util-check.firebasestorage.app',
    iosBundleId: 'com.example.checkutil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzFl78FzvFSbElM53alb0uxX4b_k6JE-4',
    appId: '1:579360616764:web:6c3222754355f4bd546e39',
    messagingSenderId: '579360616764',
    projectId: 'util-check',
    authDomain: 'util-check.firebaseapp.com',
    storageBucket: 'util-check.firebasestorage.app',
  );
}
